export const dummyProducts = [
  // ELECTRONICS
  {
    "id": 1,
    "name": "Wireless Over-Ear Headphones",
    "brand": "Wynexa Partners",
    "price": 249.99,
    "discount": 5,
    "rating": 4.8,
    "reviews": 170,
    "category": "Electronics",
    "inStock": true,
    "image": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=600&h=600",
    "description": "Premium wireless headphones with active noise cancellation and 30-hour battery life."
  },
  {
    "id": 2,
    "name": "UltraSlim 4K Laptop",
    "brand": "Wynexa Partners",
    "price": 1299.00,
    "discount": 6,
    "rating": 4.5,
    "reviews": 240,
    "category": "Electronics",
    "inStock": true,
    "image": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&q=80&w=600&h=600",
    "description": "A powerful, ultra-thin laptop featuring a brilliant 4K display and all-day battery."
  },
  {
    "id": 3,
    "name": "Pro DSLR Camera",
    "brand": "Wynexa Partners",
    "price": 1599.99,
    "discount": 10,
    "rating": 4.9,
    "reviews": 312,
    "category": "Electronics",
    "inStock": true,
    "image": "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=600&h=600",
    "description": "Capture the world in stunning detail with this professional-grade DSLR camera."
  },
  {
    "id": 4,
    "name": "Minimalist Smartwatch",
    "brand": "Wynexa Partners",
    "price": 199.50,
    "discount": 0,
    "rating": 4.4,
    "reviews": 469,
    "category": "Electronics",
    "inStock": true,
    "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=600&h=600",
    "description": "Track your fitness and stay connected with this sleek, minimalist smartwatch."
  },

  // FASHION
  {
    "id": 5,
    "name": "Classic Leather Jacket",
    "brand": "Wynexa Partners",
    "price": 189.99,
    "discount": 15,
    "rating": 4.7,
    "reviews": 130,
    "category": "Fashion",
    "inStock": true,
    "image": "https://loremflickr.com/600/600/leather,jacket/all",
    "description": "A timeless classic leather jacket designed for comfort and enduring style."
  },
  {
    "id": 6,
    "name": "Urban White Sneakers",
    "brand": "Wynexa Partners",
    "price": 119.50,
    "discount": 0,
    "rating": 4.8,
    "reviews": 575,
    "category": "Fashion",
    "inStock": true,
    "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=600&h=600",
    "description": "Step out in style with these ultra-comfortable, minimalist white sneakers."
  },
  {
    "id": 7,
    "name": "Retro Aviator Sunglasses",
    "brand": "Wynexa Partners",
    "price": 79.99,
    "discount": 5,
    "rating": 4.5,
    "reviews": 335,
    "category": "Fashion",
    "inStock": true,
    "image": "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&q=80&w=600&h=600",
    "description": "Protect your eyes with these stylish, vintage-inspired aviator sunglasses."
  },
  {
    "id": 8,
    "name": "Luxury Chronograph Watch",
    "brand": "Wynexa Partners",
    "price": 299.00,
    "discount": 0,
    "rating": 4.9,
    "reviews": 153,
    "category": "Fashion",
    "inStock": true,
    "image": "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&q=80&w=600&h=600",
    "description": "A premium timepiece featuring precision mechanics and a genuine leather strap."
  },

  // HOME & DECOR
  {
    "id": 9,
    "name": "Modern Fabric Sofa",
    "brand": "Wynexa Partners",
    "price": 799.00,
    "discount": 10,
    "rating": 4.6,
    "reviews": 89,
    "category": "Home & Decor",
    "inStock": true,
    "image": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=600&h=600",
    "description": "Upgrade your living room with this ultra-comfortable, modern fabric sofa."
  },
  {
    "id": 10,
    "name": "Geometric Floor Lamp",
    "brand": "Wynexa Partners",
    "price": 145.00,
    "discount": 0,
    "rating": 4.4,
    "reviews": 112,
    "category": "Home & Decor",
    "inStock": true,
    "image": "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600&h=600",
    "description": "Illuminate your space with this stunning, minimalist geometric floor lamp."
  },
  {
    "id": 11,
    "name": "Indoor Potted Plant",
    "brand": "Wynexa Partners",
    "price": 35.00,
    "discount": 0,
    "rating": 4.8,
    "reviews": 234,
    "category": "Home & Decor",
    "inStock": true,
    "image": "https://loremflickr.com/600/600/houseplant/all",
    "description": "Bring a touch of nature indoors with this low-maintenance, beautiful houseplant."
  },
  {
    "id": 12,
    "name": "Ergonomic Accent Chair",
    "brand": "Wynexa Partners",
    "price": 249.50,
    "discount": 5,
    "rating": 4.7,
    "reviews": 156,
    "category": "Home & Decor",
    "inStock": true,
    "image": "https://loremflickr.com/600/600/chair/all",
    "description": "A stylish and ergonomically designed accent chair perfect for reading."
  },

  // BEAUTY & CARE
  {
    "id": 13,
    "name": "Signature Floral Perfume",
    "brand": "Wynexa Partners",
    "price": 120.00,
    "discount": 0,
    "rating": 4.9,
    "reviews": 432,
    "category": "Beauty & Care",
    "inStock": true,
    "image": "https://loremflickr.com/600/600/perfume/all",
    "description": "An elegant, long-lasting floral fragrance housed in a premium glass bottle."
  },
  {
    "id": 14,
    "name": "Hydrating Night Cream",
    "brand": "Wynexa Partners",
    "price": 55.00,
    "discount": 10,
    "rating": 4.6,
    "reviews": 288,
    "category": "Beauty & Care",
    "inStock": true,
    "image": "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&q=80&w=600&h=600",
    "description": "Rejuvenate your skin overnight with this deeply hydrating, natural night cream."
  },
  {
    "id": 15,
    "name": "Vitamin C Glow Serum",
    "brand": "Wynexa Partners",
    "price": 45.00,
    "discount": 0,
    "rating": 4.8,
    "reviews": 315,
    "category": "Beauty & Care",
    "inStock": true,
    "image": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=600&h=600",
    "description": "Brighten your complexion and reduce aging signs with our organic Vitamin C serum."
  },
  {
    "id": 16,
    "name": "Luxury Spa Soap Set",
    "brand": "Wynexa Partners",
    "price": 28.00,
    "discount": 0,
    "rating": 4.7,
    "reviews": 190,
    "category": "Beauty & Care",
    "inStock": true,
    "image": "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&q=80&w=600&h=600",
    "description": "A set of handcrafted, organic spa soaps made with essential oils."
  },
  
  // MORE ELECTRONICS & GADGETS
  {
    "id": 17,
    "name": "Next-Gen Gaming Console",
    "brand": "Wynexa Partners",
    "price": 499.99,
    "discount": 0,
    "rating": 4.9,
    "reviews": 890,
    "category": "Electronics",
    "inStock": true,
    "image": "https://loremflickr.com/600/600/console,gaming/all",
    "description": "Experience true 4K gaming with ultra-fast loading speeds and immersive graphics."
  },
  {
    "id": 18,
    "name": "Mechanical RGB Keyboard",
    "brand": "Wynexa Partners",
    "price": 129.50,
    "discount": 10,
    "rating": 4.8,
    "reviews": 345,
    "category": "Electronics",
    "inStock": true,
    "image": "https://loremflickr.com/600/600/keyboard/all",
    "description": "Tactile mechanical switches with customizable per-key RGB backlighting."
  },
  {
    "id": 19,
    "name": "Smart Home Hub Display",
    "brand": "Wynexa Partners",
    "price": 89.99,
    "discount": 15,
    "rating": 4.5,
    "reviews": 210,
    "category": "Electronics",
    "inStock": true,
    "image": "https://loremflickr.com/600/600/tablet,screen/all",
    "description": "Control your entire smart home with a tap or your voice using this interactive display."
  },
  {
    "id": 20,
    "name": "Wireless Ergonomic Mouse",
    "brand": "Wynexa Partners",
    "price": 45.00,
    "discount": 0,
    "rating": 4.6,
    "reviews": 128,
    "category": "Electronics",
    "inStock": true,
    "image": "https://loremflickr.com/600/600/computer,mouse/all",
    "description": "Designed for comfort during long work sessions, featuring precise laser tracking."
  }
];
